// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: pb/interact_word_v2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InteractWordV2 is the protobuf payload inside INTERACT_WORD_V2.data.pb (base64).
// Field numbers follow bilibili live protocol / blivedm (Python) reference.
type InteractWordV2UserBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Face string `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
}

func (x *InteractWordV2UserBaseInfo) Reset() {
	*x = InteractWordV2UserBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_interact_word_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractWordV2UserBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractWordV2UserBaseInfo) ProtoMessage() {}

func (x *InteractWordV2UserBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interact_word_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractWordV2UserBaseInfo.ProtoReflect.Descriptor instead.
func (*InteractWordV2UserBaseInfo) Descriptor() ([]byte, []int) {
	return file_pb_interact_word_v2_proto_rawDescGZIP(), []int{0}
}

func (x *InteractWordV2UserBaseInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type InteractWordV2UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base *InteractWordV2UserBaseInfo `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *InteractWordV2UserInfo) Reset() {
	*x = InteractWordV2UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_interact_word_v2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractWordV2UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractWordV2UserInfo) ProtoMessage() {}

func (x *InteractWordV2UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interact_word_v2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractWordV2UserInfo.ProtoReflect.Descriptor instead.
func (*InteractWordV2UserInfo) Descriptor() ([]byte, []int) {
	return file_pb_interact_word_v2_proto_rawDescGZIP(), []int{1}
}

func (x *InteractWordV2UserInfo) GetBase() *InteractWordV2UserBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

type InteractWordV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int64  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	// 1=enter, 2=follow, 3=share, 4=special follow, 5=mutual, 6=like
	MsgType   int32                   `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Timestamp int64                   `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Uinfo     *InteractWordV2UserInfo `protobuf:"bytes,22,opt,name=uinfo,proto3" json:"uinfo,omitempty"`
}

func (x *InteractWordV2) Reset() {
	*x = InteractWordV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_interact_word_v2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractWordV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractWordV2) ProtoMessage() {}

func (x *InteractWordV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_interact_word_v2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractWordV2.ProtoReflect.Descriptor instead.
func (*InteractWordV2) Descriptor() ([]byte, []int) {
	return file_pb_interact_word_v2_proto_rawDescGZIP(), []int{2}
}

func (x *InteractWordV2) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *InteractWordV2) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *InteractWordV2) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *InteractWordV2) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InteractWordV2) GetUinfo() *InteractWordV2UserInfo {
	if x != nil {
		return x.Uinfo
	}
	return nil
}

var File_pb_interact_word_v2_proto protoreflect.FileDescriptor

var file_pb_interact_word_v2_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x77, 0x6f,
	0x72, 0x64, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x30, 0x0a, 0x1a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x56,
	0x32, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x61, 0x63,
	0x65, 0x22, 0x4c, 0x0a, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x57, 0x6f, 0x72,
	0x64, 0x56, 0x32, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32, 0x0a, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x56, 0x32, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22,
	0xa3, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x64,
	0x56, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73,
	0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a, 0x05, 0x75, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x16, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x57, 0x6f, 0x72, 0x64, 0x56, 0x32, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x75, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x69, 0x66, 0x61, 0x6e, 0x32, 0x33, 0x33, 0x33, 0x2f, 0x62, 0x6c,
	0x69, 0x76, 0x65, 0x64, 0x6d, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_interact_word_v2_proto_rawDescOnce sync.Once
	file_pb_interact_word_v2_proto_rawDescData = file_pb_interact_word_v2_proto_rawDesc
)

func file_pb_interact_word_v2_proto_rawDescGZIP() []byte {
	file_pb_interact_word_v2_proto_rawDescOnce.Do(func() {
		file_pb_interact_word_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_interact_word_v2_proto_rawDescData)
	})
	return file_pb_interact_word_v2_proto_rawDescData
}

var file_pb_interact_word_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_interact_word_v2_proto_goTypes = []any{
	(*InteractWordV2UserBaseInfo)(nil), // 0: pb.InteractWordV2UserBaseInfo
	(*InteractWordV2UserInfo)(nil),     // 1: pb.InteractWordV2UserInfo
	(*InteractWordV2)(nil),             // 2: pb.InteractWordV2
}
var file_pb_interact_word_v2_proto_depIdxs = []int32{
	0, // 0: pb.InteractWordV2UserInfo.base:type_name -> pb.InteractWordV2UserBaseInfo
	1, // 1: pb.InteractWordV2.uinfo:type_name -> pb.InteractWordV2UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_interact_word_v2_proto_init() }
func file_pb_interact_word_v2_proto_init() {
	if File_pb_interact_word_v2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_interact_word_v2_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*InteractWordV2UserBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_interact_word_v2_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*InteractWordV2UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_interact_word_v2_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*InteractWordV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_interact_word_v2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_interact_word_v2_proto_goTypes,
		DependencyIndexes: file_pb_interact_word_v2_proto_depIdxs,
		MessageInfos:      file_pb_interact_word_v2_proto_msgTypes,
	}.Build()
	File_pb_interact_word_v2_proto = out.File
	file_pb_interact_word_v2_proto_rawDesc = nil
	file_pb_interact_word_v2_proto_goTypes = nil
	file_pb_interact_word_v2_proto_depIdxs = nil
}
